name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build-prod
      - name: Run tests
        run: npm run test
      - name: Firebase deploy
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy
        env: 
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
 